export const FETCH_SET_ORDER = "FETCH_SET_ORDER";
export const FETCH_SET_ORDER_SUCCESS = "FETCH_SET_ORDER_SUCCESS";
export const FETCH_SET_ORDER_ERROR = "FETCH_SET_ORDER_ERROR";
export const RESET_ORDER = "RESET_ORDER";
